name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [master] # 或者你的默认分支名
  pull_request:
    branches: [master]

# 设置权限以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署，跳过正在进行的运行之间排队的运行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.4" # 使用你需要的 Flutter 版本
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get
        working-directory: Flutter/json_to_dart

      - name: Build web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"
        working-directory: Flutter/json_to_dart

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "Flutter/json_to_dart/build/web"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
